name: conda_rec_padroes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas>=2.3.3
  - pillow>=10.0.0
  - matplotlib>=3.7.0
  - scikit-learn=1.6.1
  - seaborn=0.12
  - tqdm>=4.65.0
